{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-plugin-gradle",
    "version": "7.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib-extra",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-plugin-gradle-7.0.4.jar",
          "url": "spotless-plugin-gradle-7.0.4.jar",
          "size": 163627,
          "sha512": "6bc0620f20d99e41157fea0e4cb4f5e2f657bdb53b766f263c6de717de641d342f37bacb11f455d6382434ba9127f9c2620265932f87e0803c457f011b045654",
          "sha256": "23557cdec130b4bb2ca2d30eda2398325e09dfe6b990d2eacd9d5f39a1dede71",
          "sha1": "75b4dd182c8513ebfdb2ca6f135d6c44210b189f",
          "md5": "522fee9fadb70e7fec7b73da11b27d48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.diffplug.durian",
          "module": "durian-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-io",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-collect",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.10.1.202505221210-r"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib-extra",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-plugin-gradle-7.0.4.jar",
          "url": "spotless-plugin-gradle-7.0.4.jar",
          "size": 163627,
          "sha512": "6bc0620f20d99e41157fea0e4cb4f5e2f657bdb53b766f263c6de717de641d342f37bacb11f455d6382434ba9127f9c2620265932f87e0803c457f011b045654",
          "sha256": "23557cdec130b4bb2ca2d30eda2398325e09dfe6b990d2eacd9d5f39a1dede71",
          "sha1": "75b4dd182c8513ebfdb2ca6f135d6c44210b189f",
          "md5": "522fee9fadb70e7fec7b73da11b27d48"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-plugin-gradle-7.0.4-javadoc.jar",
          "url": "spotless-plugin-gradle-7.0.4-javadoc.jar",
          "size": 404650,
          "sha512": "f47c15fab11ed8e77bcc964e8c9db087eafed3a1e09b94746e3526d778397c3ff86062239bbca60f49c4065b38949c879b241b9b9eed5b39dc469b89182b41c2",
          "sha256": "b5477e2f679118a90b4b132f805b2b014608afe32beba7693a275c610f325551",
          "sha1": "07564af85d5a3bbdd3fbd85f457acbe4a378af24",
          "md5": "855de3c451341a870ef93fcd8d6f77b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-plugin-gradle-7.0.4-sources.jar",
          "url": "spotless-plugin-gradle-7.0.4-sources.jar",
          "size": 80514,
          "sha512": "757abbb44d76742597d990b3a982664f27ed338d0c61b8718c0e54da50de90f4afb557413c52f41cee89d89357d2b0d8b6ccfb068936e362c0b1ac6e135d8a19",
          "sha256": "dc081cbf5fac9f4eb89a3fc78d0c366447aac5aa019877704c5753d3abeaa262",
          "sha1": "32e57805d9b0da023f91fb486b626530cce6bee3",
          "md5": "879385a36aacd7474af2d2039adf20d9"
        }
      ]
    }
  ]
}
