{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-lib-extra",
    "version": "3.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-3.1.2.jar",
          "url": "spotless-lib-extra-3.1.2.jar",
          "size": 101398,
          "sha512": "b9de8913a73a0daf85c36064f6748fbcde524f09b23a3173405d5e408431f27c6828713c830e5329a56b74f095ff56a9743894186cff8f6a51b5f5d6f09b2cb9",
          "sha256": "37c9bbde63d5cebb293321c1cfd046fc7a05cd066abda9da52aa63a8ea676f74",
          "sha1": "7ada6ce2489075c6ed26c8c52f86c9c790c8dc66",
          "md5": "63017e156aacb828a28809e4ea04feb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.diffplug.durian",
          "module": "durian-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-collect",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.10.1.202505221210-r"
          }
        },
        {
          "group": "com.googlecode.concurrent-trees",
          "module": "concurrent-trees",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "dev.equo.ide",
          "module": "solstice",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.osgi",
          "version": {
            "requires": "3.23.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-3.1.2.jar",
          "url": "spotless-lib-extra-3.1.2.jar",
          "size": 101398,
          "sha512": "b9de8913a73a0daf85c36064f6748fbcde524f09b23a3173405d5e408431f27c6828713c830e5329a56b74f095ff56a9743894186cff8f6a51b5f5d6f09b2cb9",
          "sha256": "37c9bbde63d5cebb293321c1cfd046fc7a05cd066abda9da52aa63a8ea676f74",
          "sha1": "7ada6ce2489075c6ed26c8c52f86c9c790c8dc66",
          "md5": "63017e156aacb828a28809e4ea04feb7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-3.1.2-javadoc.jar",
          "url": "spotless-lib-extra-3.1.2-javadoc.jar",
          "size": 151571,
          "sha512": "806081fa93990f4fb4d1e8fcf3d1aa42bad6a934160c7faa1000566ae0f1091d4a7701a9c5752e63f1d54ddcbf1325c6b17f213ba0ad91e88cb23ae40bfdee53",
          "sha256": "416d374ea66f1227e4f8a9e3c41d416d1019a8e28a8e2ed805ba36a3d2f65bbf",
          "sha1": "acd5378932f132a558b39009732c5aae54756507",
          "md5": "acc1f253a80a9a39e5b99243d5bc4838"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-3.1.2-sources.jar",
          "url": "spotless-lib-extra-3.1.2-sources.jar",
          "size": 40303,
          "sha512": "3b5da08e868f0cd3a3281034488cc01712a752efe6986bd0f557a1684d8c66536ce1e1f1c7810e4535910d6eab3b91ef0abe80cf9d894009cbafe36887083e1b",
          "sha256": "ae6af9e35a08ffcccdc5beb7e1f1436d2e83e719642bf56c13e2b1337c9c256a",
          "sha1": "663455d3655d16860efa34bd84fdaa1e3aa64bb4",
          "md5": "3c21034d9ddd6ad00cd8899ab5c4c973"
        }
      ]
    }
  ]
}
