# Makefile.tabrpl_thresh_relaxed
# V6 threshold sensitivity: relaxed thresholds
#   tau_warn=0.70, tau_join=0.50, tau_black=0.30
#   Slower to blacklist; lower FPR expected but slower detection

CONTIKI_PROJECT = sender
all: $(CONTIKI_PROJECT)

CONTIKI = ../contiki-ng-brpl
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

PROJECT_SOURCEFILES += ta-brpl-trust.c

CFLAGS += -DPROJECT_CONF_PATH=\"../project-conf.h\"
CFLAGS += -DBRPL_MODE=1
CFLAGS += -DTABRPL_MODE=1
CFLAGS += -DBRPL_CONF_TRUST_ENABLE=1
CFLAGS += -DCSV_VERBOSE_LOGGING=1
CFLAGS += -DTA_TRUST_TAU_WARN=700
CFLAGS += -DTA_TRUST_TAU_JOIN=500
CFLAGS += -DTA_TRUST_TAU_BLACK=300
CFLAGS += -DTRUST_MIN=500
CFLAGS += -DTA_TRUST_RESTORE_ON_RELEASE=500
CFLAGS += -DTA_TRUST_ESCAPE_TRUST_THRESHOLD=700
LDLIBS += -lm

include $(CONTIKI)/Makefile.include
