CONTIKI_PROJECT = sender
all: $(CONTIKI_PROJECT)

# Use project-wide config
PROJECT_CONF_PATH = ..

# Blacklist module
PROJECT_SOURCEFILES += brpl-blacklist.c

# Use submodule
CONTIKI = ../contiki-ng-brpl

include $(CONTIKI)/Makefile.include
