# Makefile.tabrpl_tau550
# TA-BRPL with relaxed thresholds: tau_warn=0.55, tau_join=0.40, tau_black=0.25
# Used for threshold sensitivity analysis (parameter sweep for SCI paper).

CONTIKI_PROJECT = sender
all: $(CONTIKI_PROJECT)

CONTIKI = ../contiki-ng-brpl
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

PROJECT_SOURCEFILES += ta-brpl-trust.c

CFLAGS += -DPROJECT_CONF_PATH=\"../project-conf.h\"
CFLAGS += -DBRPL_MODE=1
CFLAGS += -DTABRPL_MODE=1
CFLAGS += -DBRPL_CONF_TRUST_ENABLE=1
CFLAGS += -DCSV_VERBOSE_LOGGING=1
CFLAGS += -DTA_TRUST_TAU_WARN=550
CFLAGS += -DTA_TRUST_TAU_JOIN=400
CFLAGS += -DTA_TRUST_TAU_BLACK=250
LDLIBS += -lm

include $(CONTIKI)/Makefile.include
