# Sinkhole+Drop attacker for TA-BRPL (trust OFF — attacker node itself does not use trust)
# Scenario 2: rank-spoof + 50% selective forwarding

CONTIKI_PROJECT = sinkhole_drop_attacker
all: $(CONTIKI_PROJECT)

CONTIKI = ../contiki-ng-brpl
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

CFLAGS += -DPROJECT_CONF_PATH=\"../project-conf.h\"
CFLAGS += -DBRPL_MODE=1
CFLAGS += -DBRPL_CONF_TRUST_ENABLE=0
CFLAGS += -DATTACK_MODE=1
CFLAGS += -DATTACKER_NODE_ID=18
CFLAGS += -DSINKHOLE_RANK_DELTA=1
CFLAGS += -DATTACK_WARMUP_SECONDS=350
CFLAGS += -DSINKHOLE_DIO_PERIOD_SECONDS=15
CFLAGS += -DATTACK_DROP_PCT=50
CFLAGS += -DCSV_VERBOSE_LOGGING=1

include $(CONTIKI)/Makefile.include
