# Makefile.tabrpl_tau450
# TA-BRPL with permissive thresholds: tau_warn=0.45, tau_join=0.33, tau_black=0.20
# Used for threshold sensitivity analysis (parameter sweep for SCI paper).

CONTIKI_PROJECT = sender
all: $(CONTIKI_PROJECT)

CONTIKI = ../contiki-ng-brpl
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

PROJECT_SOURCEFILES += ta-brpl-trust.c

CFLAGS += -DPROJECT_CONF_PATH=\"../project-conf.h\"
CFLAGS += -DBRPL_MODE=1
CFLAGS += -DTABRPL_MODE=1
CFLAGS += -DBRPL_CONF_TRUST_ENABLE=1
CFLAGS += -DCSV_VERBOSE_LOGGING=1
CFLAGS += -DTA_TRUST_TAU_WARN=450
CFLAGS += -DTA_TRUST_TAU_JOIN=330
CFLAGS += -DTA_TRUST_TAU_BLACK=200
LDLIBS += -lm

include $(CONTIKI)/Makefile.include
