{
  "formatVersion": "1.1",
  "component": {
    "group": "com.formdev",
    "module": "flatlaf",
    "version": "3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flatlaf-3.6.jar",
          "url": "flatlaf-3.6.jar",
          "size": 925551,
          "sha512": "08ac1c8bbe9574212a0d1230778676de5e0d4231380948d94e07e73cc80eea0cebae684df4759d32bc656ebc38cb0f72583e3a51e9927be167738a44963d1cb9",
          "sha256": "2df1e3183600262a15f76aa4ae5acc2c154e884f7672bddaaac66842a37cf3f0",
          "sha1": "049f388b57537c286b466dee84a6d01ba57a59e9",
          "md5": "e315e1591bbe24ca9f380d537964fa99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatlaf-3.6.jar",
          "url": "flatlaf-3.6.jar",
          "size": 925551,
          "sha512": "08ac1c8bbe9574212a0d1230778676de5e0d4231380948d94e07e73cc80eea0cebae684df4759d32bc656ebc38cb0f72583e3a51e9927be167738a44963d1cb9",
          "sha256": "2df1e3183600262a15f76aa4ae5acc2c154e884f7672bddaaac66842a37cf3f0",
          "sha1": "049f388b57537c286b466dee84a6d01ba57a59e9",
          "md5": "e315e1591bbe24ca9f380d537964fa99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatlaf-3.6-sources.jar",
          "url": "flatlaf-3.6-sources.jar",
          "size": 634381,
          "sha512": "e8dd56650c077d9dcc9a0bb0e1a9f823020d38fcff69593e50ff2d6d0e7f4c458fe173fc0c9f67efd317bdaed8fcf2a622de72f5e61b94aebf235aeb7db6694b",
          "sha256": "0f6a2355cc0ebc4e23f828767a7f430ca4de94861304892a110f05ff747de6a3",
          "sha1": "6665f93de6b10204d9e106e4dd755d825de0b0e0",
          "md5": "d63415aa7a9797e2285fdd105649ccf1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatlaf-3.6-javadoc.jar",
          "url": "flatlaf-3.6-javadoc.jar",
          "size": 1956976,
          "sha512": "12ca9ad5550e539535993d2c906d21de67b5c04e43a51a0e67ca929786f7b4e7793590d78303463c327b015e0b6c1c64537d0106a66be4a075e7d1cdc451bc34",
          "sha256": "e250e6f4b7ec6ef929dce4a48bd2398f15eefa8c8e6d9e8d2155763e15a31dac",
          "sha1": "8e4d579c855b084371b0073c02e30ea18d370d16",
          "md5": "d5d1e3d047d6d1e7c3fa9d0c8ea0b268"
        }
      ]
    }
  ]
}
