<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>RPL MRHOF Simulation (Random)</title>
    <randomseed>123456</randomseed>
    <motedelay_us>1000000</motedelay_us>
    <radiomedium>
      org.contikios.cooja.radiomediums.UDGM
      <transmitting_range>45.0</transmitting_range>
      <interference_range>90.0</interference_range>
      <success_ratio_tx>1.0</success_ratio_tx>
      <success_ratio_rx>1.0</success_ratio_rx>
    </radiomedium>
    <events>
      <logoutput>40000</logoutput>
    </events>
    <motetype>
      org.contikios.cooja.contikimote.ContikiMoteType
      <identifier>root_type</identifier>
      <description>Root Node</description>
      <source>[CONFIG_DIR]/../motes/receiver_root.c</source>
      <commands>make -C ../motes -f Makefile.receiver -j receiver_root.cooja TARGET=cooja</commands>
      <moteinterface>org.contikios.cooja.interfaces.Position</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.Battery</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiVib</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiMoteID</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRS232</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiBeeper</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiIPAddress</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRadio</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiButton</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiPIR</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiClock</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiLED</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiCFS</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiEEPROM</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.MoteAttributes</moteinterface>
    </motetype>
    <motetype>
      org.contikios.cooja.contikimote.ContikiMoteType
      <identifier>sender_type</identifier>
      <description>Sender Node</description>
      <source>[CONFIG_DIR]/../motes/sender.c</source>
      <commands>make -C ../motes -f Makefile.sender -j sender.cooja TARGET=cooja DEFINES=SEND_INTERVAL_SECONDS=30,WARMUP_SECONDS=120</commands>
      <moteinterface>org.contikios.cooja.interfaces.Position</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.Battery</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiVib</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiMoteID</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRS232</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiBeeper</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiIPAddress</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRadio</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiButton</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiPIR</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiClock</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiLED</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiCFS</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiEEPROM</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.MoteAttributes</moteinterface>
    </motetype>
    <motetype>
      org.contikios.cooja.contikimote.ContikiMoteType
      <identifier>attacker_type</identifier>
      <description>Selective Forwarding Attacker</description>
      <source>[CONFIG_DIR]/../motes/attacker.c</source>
      <commands>make -C ../motes -f Makefile.attacker -j attacker.cooja TARGET=cooja DEFINES=ATTACK_DROP_PCT=0,WARMUP_SECONDS=120</commands>
      <moteinterface>org.contikios.cooja.interfaces.Position</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.Battery</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiVib</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiMoteID</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRS232</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiBeeper</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiIPAddress</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRadio</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiButton</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiPIR</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiClock</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiLED</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiCFS</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiEEPROM</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>org.contikios.cooja.interfaces.MoteAttributes</moteinterface>
    </motetype>
    <!-- Node 1: Root -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>0.00</x>
        <y>0.00</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>1</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>root_type</motetype_identifier>
    </mote>
    <!-- Node 2: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-24.53</x>
        <y>29.35</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>2</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 3: Attacker -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>20.00</x>
        <y>0.00</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>3</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>attacker_type</motetype_identifier>
    </mote>
    <!-- Node 4: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-26.01</x>
        <y>70.80</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>4</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 5: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>53.36</x>
        <y>-11.96</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>5</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 6: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-10.94</x>
        <y>69.39</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>6</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 7: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>0.78</x>
        <y>5.41</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>7</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 8: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>15.54</x>
        <y>-11.48</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>8</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 9: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>54.02</x>
        <y>-34.65</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>9</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 10: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-11.56</x>
        <y>-20.13</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>10</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 11: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-50.56</x>
        <y>59.75</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>11</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 12: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>95.27</x>
        <y>1.91</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>12</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 13: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-50.17</x>
        <y>23.79</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>13</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 14: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>1.80</x>
        <y>80.02</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>14</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 15: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>39.71</x>
        <y>-26.73</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>15</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 16: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-85.51</x>
        <y>0.56</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>16</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 17: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-32.29</x>
        <y>37.32</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>17</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 18: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-49.58</x>
        <y>37.37</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>18</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 19: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>27.16</x>
        <y>24.81</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>19</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 20: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>45.48</x>
        <y>43.33</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>20</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 21: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>89.79</x>
        <y>3.24</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>21</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 22: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>25.59</x>
        <y>-15.05</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>22</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 23: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>83.95</x>
        <y>-22.63</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>23</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 24: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-72.92</x>
        <y>-17.52</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>24</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 25: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>68.35</x>
        <y>-76.46</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>25</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 26: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-45.44</x>
        <y>-50.63</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>26</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 27: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-35.37</x>
        <y>16.17</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>27</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 28: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-10.59</x>
        <y>-74.30</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>28</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 29: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-12.54</x>
        <y>59.44</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>29</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 30: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>73.03</x>
        <y>46.99</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>30</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 31: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>72.36</x>
        <y>86.48</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>31</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 32: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>61.16</x>
        <y>0.36</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>32</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 33: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-89.20</x>
        <y>-45.33</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>33</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 34: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>68.60</x>
        <y>69.35</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>34</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 35: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>45.22</x>
        <y>-86.02</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>35</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 36: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-90.35</x>
        <y>-17.26</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>36</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 37: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-73.52</x>
        <y>67.68</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>37</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 38: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>99.95</x>
        <y>32.51</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>38</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 39: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-84.35</x>
        <y>23.10</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>39</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 40: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>4.21</x>
        <y>14.63</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>40</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 41: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>55.71</x>
        <y>-66.31</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>41</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 42: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-15.09</x>
        <y>14.37</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>42</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 43: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>68.54</x>
        <y>-1.35</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>43</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 44: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-67.42</x>
        <y>44.92</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>44</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 45: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-84.92</x>
        <y>-52.65</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>45</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 46: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>40.05</x>
        <y>66.25</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>46</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 47: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-26.14</x>
        <y>91.60</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>47</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 48: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>68.86</x>
        <y>62.09</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>48</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 49: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>-13.53</x>
        <y>8.59</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>49</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 50: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>37.58</x>
        <y>-2.66</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>50</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
    <!-- Node 51: Sender -->
    <mote>
      <interface_config>
        org.contikios.cooja.interfaces.Position
        <x>56.90</x>
        <y>56.59</y>
        <z>0.0</z>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiMoteID
        <id>51</id>
      </interface_config>
      <interface_config>
        org.contikios.cooja.contikimote.interfaces.ContikiRadio
        <bitrate>250.0</bitrate>
      </interface_config>
      <motetype_identifier>sender_type</motetype_identifier>
    </mote>
  </simulation>
  <plugin>
    org.contikios.cooja.plugins.SimControl
    <width>280</width>
    <z>4</z>
    <height>160</height>
    <location_x>400</location_x>
    <location_y>0</location_y>
  </plugin>
  <plugin>
    org.contikios.cooja.plugins.ScriptRunner
    <plugin_config>
      <script>// Auto-generated Cooja script
TIMEOUT(@SIM_TIME_MS@, log.log("SIMULATION_FINISHED\n"); log.testOK(); );
log.log("Headless simulation started\n");
log.log("Duration: @SIM_TIME_SEC@s\n");
log.log("Nodes: " + sim.getMotesCount() + "\n");
while(true) {
  YIELD();
  if(msg != null) {
    log.log(msg + "\n");
  }
}
</script>
    </plugin_config>
  </plugin>
  <plugin>
    org.contikios.cooja.plugins.LogListener
    <plugin_config>
      <filter />
      <formatted_time />
      <coloring />
    </plugin_config>
    <width>1179</width>
    <z>0</z>
    <height>704</height>
    <location_x>679</location_x>
    <location_y>0</location_y>
  </plugin>
</simconf>
